### ISSUE TITLE
function: channelcreate: Nie posiadasz wymaganej grupy do założenia kanału

### ISSUE THREAD

**Issue by p0p3j** [Majcon94/TS3Bot#11]
Dziś wykonałem aktualizację z '415' na '416'
Mimo wrzuceniu do configu:
`'cgid'		=> [31, 32, 6],	`

po wejściu na kanał odpowiedzialny za utworzenie kanału prywatnego wyrzuca:
`Nie posiadasz wymaganej grupy do założenia kanału.`

Oczywiście należę do jednej z powyższych grup (należenie do wszystkich również nie działa).
Tymczasowo podmieniłem channelcreate.php na wersję z 415. Nowe rozwiązanie dot. zakładanie kanałów prywatnych dla użytkowników zarejestrowanych jest fajnym pomysłem pod warunkiem że będzie działać ;)

**Comment by Majcon94** [comment]
Zlokalizowałem już błąd postaram się wrzucić na gita niedługo

**Comment by Majcon94** [comment]
Błąd naprawiony i pliki  zostały już wrzucone na githuba możesz sprawdzić ; )
