### ISSUE TITLE
Bot nie daje channel admina 

### ISSUE THREAD

**Issue by Mrmatiiii** [Majcon94/TS3Bot#5]
Bocik nie daje channela przy tworzeniu ;c

**Comment by Majcon94** [comment]
Prawdopodobnie błąd został naprawiony ;)

**Comment by Qunir** [comment]
Na pewno dobrze go skonfigurowałeś?
Proszę skopiuj to jeszcze raz tylko najpierw wklej później zaznacz cały tekst i dopiero kliknij w 'Insert Code' będzie bardziej czytelniejszy niż teraz.
Po za tym widzę że masz ustawione:
```
					'name_online' => true,	//Czy ma zmieniać nazwę kanału.
					'time_info' => false,	//Czy ma wyświetlać czas offline
					'channel_info' => false	//Czy ma wyświetlać nazwę kanału.
```
Może warto włączyć 'time_info' i 'channel_info' na true?
