### ISSUE TITLE
groupOnline

### ISSUE THREAD

**Issue by p0p3j** [Majcon94/TS3Bot#5]
Funkcja nie zmienia statusu administratorów w opisie kanału. Odświeża się to jedynie w przypadku restartu bota (./start.sh restart).

Pliki funkcji bez zmian, config ponizej.

```
//groupOnline() Funkcja wyĹ›wietla listÄ™ osĂłb z podanej grupy w opisie na kanale o podanym ID.
		'functions_GroupOnline' => [
			'on'		=> true,	//true - wĹ‚Ä…czona false - wyĹ‚Ä…czona
			'inst'		=> 1, //ID Instancji 
			'cid'       => [
				7 => [	//ID KanaĹ‚u.
					'gid' => [
						6	=> '',
						33	=> ''
					],	//ID kanaĹ‚u, na ktĂłrym ma byÄ‡ zmieniany opis oraz nazwa grupy.
					'title' => '[CENTER][B][SIZE=14]Administracja[/SIZE][/B][/CENTER]\n\n',
					'channel_name' => 'Administracja ({1} Online)',	//Nazwa kanaĹ‚u {1} - oznacza liczbÄ™ online {2} - oznacza Ĺ‚Ä…cznÄ… liczbÄ™ osĂłb.
					'name_online' => true,	//Czy ma zmieniaÄ‡ nazwÄ™ kanaĹ‚u.
					'time_info' => false,	//Czy ma wyĹ›wietlaÄ‡ czas offline
					'channel_info' => false	//Czy ma wyĹ›wietlaÄ‡ nazwÄ™ kanaĹ‚u.
				]
			]
		],
```

**Comment by p0p3j** [comment]
Dużo syfu robi się na czacie gdy odświeża gdzie siedzi aktualnie administrator. Wolę aby funkcja wyświetlała jedynie kto jest online. 

Jeżeli chodzi o config to cid i gid prawidłowe. Pokazuje te rangi co ma i w poprawnym kanale, jednak nie odświeża statusu online/offline.

**Comment by Qunir** [comment]
Wydaje mi się żeby Ci pokazywało kto jest online/offline musisz włączyć 'time_info'. Nie znam się na programowaniu nie wiem dokładnie jak został napisany bot ale tylko ta funkcja wskazuje na to co chcesz zrobić. Jest napisane: //Czy ma wyświetlać czas offline - ale na pewno chodzi też o online jak ktoś jest. Bez tego pewnie Ci nie aktualizuje.

**Comment by p0p3j** [comment]
Nope.
time_info • dodaje timer jeżeli ktoś z administracji jest offline
channel_Info • dodaje informację na jakim kanale siedzi administrator.

**Comment by Majcon94** [comment]
Coś tam poprawiłem sprawdź teraz czy działa
